### ISSUE TITLE
[UI][MySQL] UI for checking balance

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#10]
[Checking balance]
1. request DB to get balance
2. show balance
3. return to previous menu

**[MySQL]**
**1. balance = get_balance(user_id || account_num)**

**Comment by ggoboogy** [comment]
2 & 3 are finished.
See : [2f6d005](https://github.com/KAIST-IS521/TeamOne/commit/2f6d00541f9ab8177f3ada4c747a1e9a87c16286)

**Comment by ian0371** [comment]
I think account number is unnecessary thus it was removed.
**balance = get_balance(user_id)**
returns `False` when user does not exist,
otherwise, returns balance (int)
See: 7441692

**Comment by ggoboogy** [comment]
Good. working well
See : [88ff78d](https://github.com/KAIST-IS521/TeamOne/commit/88ff78d21e7c6c147ee18ca367b8d6aa2364d81d)
