### ISSUE TITLE
[UI][MySQL] UI for checking transaction history

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#11]
[Checking transaction history]
1. request DB to get transaction history
2. show histroy using a table
3. return to previous menu

**[MySQL]**
**1. history_array= get_all_transaction(user_id || account_num)**
- history_array should contain: 
    - date
    - sender/receiver
    - withdrawn amount
    - deposited amount
    - balance after transaction

**Comment by ggoboogy** [comment]
2 & 3 are finished.
See: [cf31db5](https://github.com/KAIST-IS521/TeamOne/commit/cf31db57dab5bc14cfa63c1f247f4f6fc1839155)

**Comment by asdfljh** [comment]
@ggoboogy 1bdba56917923d43c377c2885e793c6e52b652f1 구현 완료했습니다. 확인 후 close해주세요.

**Comment by ggoboogy** [comment]
working well except balance after transaction
See: [ae22551](https://github.com/KAIST-IS521/TeamOne/commit/ae22551cafb1c7d8516dc6081bf88cc85850242b)
