### ISSUE TITLE
[UI][MySQL] UI for money transfer

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#12]
[Transfer]
1. get receiver
2. get amount
3. request DB to get balance & check balance >= amount
4. request DB to confirm receiver is valid or not
5. get reconfirmation from user
6. show result & return to previous menu

**[MySQL]**
**1. balance = get_balance(user_id)**
**2. boolean = is_vaild_receiver(receiver)**
**3. boolean(success/fail) = store_transaction(user_id, receiver, amount, date, balance after transaction)**

**Comment by ggoboogy** [comment]
1, 2, 5, 6 are finished.
See : [2f6d005](https://github.com/KAIST-IS521/TeamOne/commit/2f6d00541f9ab8177f3ada4c747a1e9a87c16286)

**Comment by ian0371** [comment]
[MySQL]
1: 076c76b
2: 7394cc6
3: 2b12320
store_transaction에 #30처럼 message 필요하고,
user_id는 송신인 ID로, receiver는 수신인 계좌번호, amount는 송금액(양수), date와 balance after ~도 삭제되었습니다.
transaction 저장과 동시에 송신인과 수신인의 balance가 업데이트됩니다.

**Comment by ggoboogy** [comment]
@ian0371 
store_transaction 함수 내
144: `if not self.update_balance(sender, -amount):` 에서
-amount 부분 의도하신바 인가요?
-때문에 에러가 발생하는듯 합니다.

**Comment by ian0371** [comment]
계좌 기반 송금에서 ID 기반 송금으로 변경했습니다.
수신인의 계좌번호 대신 ID를 적으면 됩니다.
See: 9835762

**Comment by ggoboogy** [comment]
Thank you. working well.
See : [385d941](https://github.com/KAIST-IS521/TeamOne/commit/385d9414ea54f653c71665a98503cd595eb59577)
