### ISSUE TITLE
[UI][MySQL] UI for editing user info & removing account

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#13]
[Edit user info & Remove account]
1. get password for identity verification
2. get option 'edit user info' or 'remove account'
3. edit user info
3-1. get option to edit
3-2. make SQL query to modify user info
3-3. show result & return to previous menu
4. remove account
4-1. get reconfirm from user
4-2. show result & return to previous menu

**[MySQL]**
**1. boolean = match_id_pw(id, pw)**
**2. info_array = get_every_user_info(id)**
       **(password should be included.)**
**3. boolean(success/fail) = store_user_info_modification(info_array)**
**4. boolean(success/fail) = remove_user_account(user_id || account_num)**

**Comment by ggoboogy** [comment]
1, 2, 4 are finished.
See : [1d5c1b2](https://github.com/KAIST-IS521/TeamOne/commit/1d5c1b299ec72238aacbaba565a586bf6ef307e7)

**Comment by asdfljh** [comment]
@ian0371 이 부분 제가 할게요.
@ggoboogy store할때 parameter를 (user_id, info_array)로 하고, info_array는 dictionary(user_pw, account_num, github_id, email, mobile)로 해도 될까요? - user_id, balance 제외

**Comment by ggoboogy** [comment]
[UI]
3 are finished.
See: [e430db1](https://github.com/KAIST-IS521/TeamOne/commit/e430db1fce5f4575818bd51ced7ee32dd1568a18)

**Comment by ggoboogy** [comment]
@asdfljh account number랑 github_id도 사실상 변경되지 않아야하는 정보이므로 dictionary(user_pw, email, mobile)만 담는게 좋을거 같습니다.

**Comment by asdfljh** [comment]
@ggoboogy 이제야 봤네요 ㅠㅠ get_every_user_info와 같이 쓰시는 줄 알고 편의를 고려하여 그렇게 넘겨줬는데 수정하도록 하겠습니다.

**Comment by ggoboogy** [comment]
@asdfljh 헉 이미 그렇게 구현하셨으면 수정 안하셔도 될거같아요..!

**Comment by asdfljh** [comment]
@ggoboogy b80d50aebee6e9055692b7c9a2a19a6fbca57a02 edit_user 부분 구현 완료했습니다.
확인 후 close해주세요.

**Comment by ggoboogy** [comment]
Good. working well
Thank you
See: [5f9b3ba](https://github.com/KAIST-IS521/TeamOne/commit/5f9b3bac0e3ee412f4d76c212a266c5e584db0f2)
