### ISSUE TITLE
[UI][MySQL] UI for register

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#14]
[Register]
1. get user name
2. request DB to confirm whether existing ID or not
3. get password
4. get email
5. get phone number
6. get reconfirmation to register from user
7. show result & return to previous menu

**[MySQL]**
**1. boolean = is_existing_id(inputted_id)**
**2. boolean(success/fail) = store_user(user_id, user_pw, account_num, github_id, email, mobile, balance)**

**Comment by asdfljh** [comment]
아래 링크를 참고하신 후, 피드백 주시면 감사하겠습니다.
Reference: https://github.com/KAIST-IS521/TeamOne/issues/5#issuecomment-301339136, 50e543dad79ddb670938b66de724e7b9ff673a8b

**Comment by asdfljh** [comment]
@ian0371 이 부분 제가 할게요.

**Comment by ian0371** [comment]
네 그렇게해주세요
Store할때는 cursor.commit해줘야해요
Pymysql문서보심돼요

**Comment by asdfljh** [comment]
@ian0371 auth_table (github_id, pgp_key, reg_flag) script도 만들고 시작하겠습니다.

**Comment by asdfljh** [comment]
@ggoboogy is_existing_id(ea5ded046bc62234071b4529ec0e5a0fecdcbe31), store_user(abb72d80cab2d61e7af91fcf95a17f7023a0a4a5) 구현 완료했습니다.

해결되지 않은(?) 관련 issue: https://github.com/KAIST-IS521/TeamOne/issues/19

**Comment by ggoboogy** [comment]
1, 3, 4, 5, 6, 7 are finished.
see: [9b45758](https://github.com/KAIST-IS521/TeamOne/commit/9b4575896da7c8e67ac09234e4bafb9ef85d10bf)

**Comment by asdfljh** [comment]
@ggoboogy 이 부분에서 이 github_id의 등록여부를 확인하는 함수가 필요한 것 같습니다. 확인해보시고 피드백 주셔요.

**Comment by ggoboogy** [comment]
@asdfljh  github_id 의 등록여부가... PGP 인증 말씀하시는건가요?

**Comment by asdfljh** [comment]
@ggoboogy 같은 github_id 당 한번만 1000원을 주는 부분이요.

**Comment by ggoboogy** [comment]
@asdfljh  그부분은 잠시 보류할게욧 
그리고 혹시 store_user() 함수에서 account number의 경우 사용자에게 입력받는게 아니라 서버에서 다른 사용자와 겹치지않는 유니크넘버로 생성해서 저장해야하는데 지금 제가 넘겨줘야하게끔 되어있더라구요... 이부분 수정 부탁드립니다.ㅜㅜ

**Comment by asdfljh** [comment]
@ggoboogy 92f1700dcce9bc955280deb35f607ffb2e5d8465 account_num 자동생성 추가했는데 확인부탁드려요.

**Comment by ggoboogy** [comment]
@asdfljh  store_user 함수에서 계속 false 리턴이 되는데, 혹시 테스트해보실때 잘 되던가요? user_table 내의 항목들 순서랑 INSERT 할때 항목 순서가 다르던데 이부분은 상관 없는건가요?

**Comment by asdfljh** [comment]
@ggoboogy 항목들 순서라는 것이 어떤건지 알 수 있을까요? 제 local에서 테스트할 경우에는 문제가 없긴했어요. False 발생 이유 중 제가 현재 파악하고 있는건 입력하는 github_id가 auth_table에 없는 경우 or user_id가 겹치는 경우였습니다.

혹시 github_id가 auth_table에 없어서 발생하는 경우라면, 테스트 전에 db/reg_pubkey.py를 한번 실행시켜주세요. 확인해보시고 답변 부탁드립니다.

**Comment by ggoboogy** [comment]
@asdfljh  github_id가 auth_table에 없어서 발생하는 문제였네요ㅠ 감사합니다 해결되었어요.

**Comment by ggoboogy** [comment]
Working well
See: [4f5f878](https://github.com/KAIST-IS521/TeamOne/commit/4f5f8780c9c953ad9a495fe145f6d214ad30086f)
