### ISSUE TITLE
[UI] Hiding the inputted password

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#17]
I think the password that the user inputs needs to be hidden by using asterisks.
Currently, `UI` shows the password in a plain-text manner. 
If possible and necessary, how about displaying the inputted password in a hidden manner.

**Comment by asdfljh** [comment]
아래 링크 참고하시면 좋을 것 같습니다.
reference: https://docs.python.org/3/library/getpass.html#getpass.getpass

**Comment by ggoboogy** [comment]
getpass 서버측에서도 사용 가능한것 맞나요?
방금 확인해봤는데, 아무래도 소켓통해서는 적용이 불가능한것 같고 사용하려면 클라이언트측 프로그램을 따로 만들어야하는것 같아요.

**Comment by asdfljh** [comment]
소켓 통신일때를 찾아봐야했는데 잘못찾아드렸네요 ㅠㅠ
소켓 통신일 때로 찾아보고 있는데 좋은 방법은 아직 못 찾았어요.

**Comment by ian0371** [comment]
netcat으로 접속할텐데 이 경우엔 이를 해결 못 할 것 같네요.

**Comment by ggoboogy** [comment]
네 netcat으로 하는 경우 다른 방법은 없는듯합니다 ㅠ

**Comment by jmpark81** [comment]
네, 이 부분은 그냥 생략하고 진행해도 무방할 것 같아요.
찾아보시느라 고생 많으셨어요.
