### ISSUE TITLE
Team PGP key

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#18]
We need PGP key for banking system.

**Comment by james010kim** [comment]
New PGP key for banking system.
Please check attached file.

[server.key.gpg.zip](https://github.com/KAIST-IS521/TeamOne/files/1003235/server.key.gpg.zip)

**Comment by james010kim** [comment]
팀원들 5명의 pub key로 아래와 같이 암호화했는데, 안풀리네요. 도움이 필요합니다. 

`vagrant@deb32:~/shared/teamone$ gpg --output /tmp/server.key.pgp -r james010kim@gmail.com -r jihyeon.yoon@kaist.ac.kr -r jmpark81@kaist.ac.kr -r ian0371@gmail.com -r cjdhlds08@gmail.com -e server.key
gpg: B4472679: There is no assurance this key belongs to the named user

pub  2048R/B4472679 2017-03-08 Jiho Lee <cjdhlds08@gmail.com>
 Primary key fingerprint: 56BD DEA1 14CC E4D9 6CAC  BD5D 6EC1 818C D6DE C276
      Subkey fingerprint: 3890 8757 E0D1 8C0B CC89  4055 F110 62D9 B447 2679

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
gpg: 33E664A3: There is no assurance this key belongs to the named user

pub  4096R/33E664A3 2017-03-08 ChiHyun Song <ian0371@gmail.com>
 Primary key fingerprint: 0F5A 87A3 0776 C602 70DF  B73E 09D4 C532 4694 1CD1
      Subkey fingerprint: 3DB8 F8DD 14E7 8621 EE2E  6028 093A 4485 33E6 64A3

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
gpg: EB16F12E: There is no assurance this key belongs to the named user

pub  2048R/EB16F12E 2017-03-08 Jaemin Park (KAIST) <jmpark81@kaist.ac.kr>
 Primary key fingerprint: 8663 1911 5DDC 296B 5C92  A996 7F83 6E86 C998 F9A9
      Subkey fingerprint: AE29 F1BE 4FEE 2712 06DF  235E 8D06 FC5D EB16 F12E

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
gpg: 6A6D5F28: There is no assurance this key belongs to the named user

pub  2048R/6A6D5F28 2017-03-08 Ji Hyeon Yoon (PGP keys for testing) <jihyeon.yoon@kaist.ac.kr>
 Primary key fingerprint: 0A4E 1196 0B64 4CD9 3710  7B1E 4633 879D 4D73 3623
      Subkey fingerprint: B632 D936 33E3 2DCA 60A9  DC9E 4B0F 8047 6A6D 5F28

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
gpg: 2081918C: There is no assurance this key belongs to the named user

pub  2048R/2081918C 2017-03-08 Jangha Kim <james010kim@gmail.com>
 Primary key fingerprint: 0D76 6E7D CB82 22AA E50D  69D6 8C5A 5128 441C B992
      Subkey fingerprint: 790D 3E6F 27E4 79CB 07AF  46ED 1482 DA0B 2081 918C

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
File `/tmp/server.key.pgp' exists. Overwrite? (y/N) y
vagrant@deb32:~/shared/teamone$ gpg --output /tmp/server.key -d /tmp/server.
server.key.pgp  server.pgp      
vagrant@deb32:~/shared/teamone$ gpg --output /tmp/server.key -d /tmp/server.key.pgp 
gpg: encrypted with 2048-bit RSA key, ID B4472679, created 2017-03-08
      "Jiho Lee <cjdhlds08@gmail.com>"
gpg: encrypted with 4096-bit RSA key, ID 33E664A3, created 2017-03-08
      "ChiHyun Song <ian0371@gmail.com>"
gpg: encrypted with 2048-bit RSA key, ID EB16F12E, created 2017-03-08
      "Jaemin Park (KAIST) <jmpark81@kaist.ac.kr>"
gpg: encrypted with 2048-bit RSA key, ID 6A6D5F28, created 2017-03-08
      "Ji Hyeon Yoon (PGP keys for testing) <jihyeon.yoon@kaist.ac.kr>"
gpg: encrypted with 2048-bit RSA key, ID 2081918C, created 2017-03-08
      "Jangha Kim <james010kim@gmail.com>"
gpg: decryption failed: secret key not available
vagrant@deb32:~/shared/teamone$ 
`

**Comment by ian0371** [comment]
gpg -K 해보시면 가지고있는 secret key 목록이 뜨는데 여기에 james010kim@gmail.com이 있는지 확인해보셔야할듯해요.
참고로 저는 잘 풀렸어요.

**Comment by james010kim** [comment]
`vagrant@deb32:/tmp$ gpg -K
/home/vagrant/.gnupg/secring.gpg
--------------------------------
sec   2048R/441CB992 2017-03-08
uid                  Jangha Kim <jangha@kaist.ac.kr>
uid                  Jangha Kim <james010kim@gmail.com>
`
secret key는 있는데 not available 이라고 나오네요. 
잘 풀리니, close 하겠습니다.

**Comment by jmpark81** [comment]
이 키는 공개키와 개인키가 합쳐진 형태인가요?
`engineering.tex`에 언급된 것(The server sends the encrypted data along with its public key1, and the user decrypts it with her/his private key to get the original random number. The user now encrypts the random number _with the server’s public key_ and send the encrypted message back to the server. Server can verify whether this user has successfully decrypted the message.)처럼 PGP 인증 과정에서 서버의 공개키를 클라이언트에게 전달해야 하기에 만약 합쳐진 것이라면 분리한 형태로 변경하는 것이 편리할 것 갔습니다. 
다른 분들의 생각은 어떠신지요?

**Comment by ian0371** [comment]
네 저도 루트디렉토리에 공개키 공개해야한다고 생각해요.

**Comment by james010kim** [comment]
루트디렉토리에 공개키 공개를 위한 풀리퀘를 올렸습니다.
다른 분이 Merge 부탁드립니다.
[Pull Request](https://github.com/KAIST-IS521/TeamOne/pull/29)

**Comment by ian0371** [comment]
merge하였습니다.
