### ISSUE TITLE
[PyMySQL] bankDB 클래스 객체 동기화(?)

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/TeamOne#19]
is_existing_id 함수 작업 테스트하는 도중에 생긴 이슈인데요.
bankDB 객체 생성 후에 user_table에 insert한 instance에 대해서는 exist하다고 업데이트가 되지 않더라구요? 원래 이런건가요?

**Comment by asdfljh** [comment]
![image](https://cloud.githubusercontent.com/assets/26140051/26103059/c5e3f5fc-3a72-11e7-892c-cdd361d7baf2.png)
p로 user_id가 abcabc인 계정을 만들어서 store한 후에 q에서 is_existing_id하면 false가 나오는 현상을 질문드리는겁니다.

**Comment by ian0371** [comment]
autocommit=True로 바꾸니 해결되는 것 같네요.
61ea62e 참고하세요.
아마 이렇게되면 `self.conn.commit()` 빼줘도 될듯 하네요 (확인은 안 해봤어요)

**Comment by asdfljh** [comment]
잘 되는거 같네욥!
