### ISSUE TITLE
[Auth] gnupg verify seems to does not work.

### ISSUE THREAD

**Issue by james010kim** [KAIST-IS521/TeamOne#20]
flag update message를 제 credential을 사용하여 만들어 verify signature 기능을 구현 중인데,
gnupg.verify .verify_data .verify_file 모두 에러만 리턴합니다.

command-line 에서 gpg --verify 하면 verified 라고 잘 나옵니다.
TeamFive 코드를 살펴보니, 그냥 verify_data를 사용했던데, 저만 안되는건가요? ㅋㅋ

gnupg.py를 살펴보니, _open_subprocess 하던데 빛이 보이지 않는다면 이길로 가야겠습니다.

**Comment by jmpark81** [comment]
https://pythonhosted.org/gnupg/gnupg.html?highlight=verify#gnupg.GPG.verify
위 사이트를 참고해서 해보시면 어떨까요? 
저희가 사용하는 모듈은 `gnupg`이며 참고하신 API는 `python-gnupg`인 것 같습니다.

**Comment by james010kim** [comment]
verify() 에 text armor 된 PGP message 를 넣어주니 잘 동작합니다. [fb53253](https://github.com/KAIST-IS521/TeamOne/pull/50/commits/fb532533c2c3738daee64a682591e8a2521500de)
고맙습니다. 
issue를 close합니다.
