### ISSUE TITLE
[Auth][UI] User Registration

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#25]
`engineering.tex`에 의하면, 다음과 같이 언급되어 있습니다.

"In registration menu, the client should first authenticate him or her with PGP key, as described in (§1.7). When the identity is authenticated, the client can send a username and a password to create a new user account." 

"1.7 Authentication
Since we have everyone’s PGP public key, we will use a simple PGP-key based authentication in this activity. First, a server asks your github ID. When a user provides their ID, the server creates a large random number and sends encrypts the number with the user’s public key. The server sends the encrypted data along with its public key1, and the user decrypts it with her/his private key to get the original random number. The user now encrypts the random number with the server’s public key and send the encrypted message back to the server. Server can verify whether this user has successfully decrypted the message.
Throughout this document, whenever we say that you have to implement an authentication system, it means you have to implement this PGP-based authentication."

제가 이해한 바에 의하면, `2. Register` 선택 시 `github_id`를 요청하는 UI가 표시되어야 하고, 입력된 `github_id`를 이용하여 PGP 인증을 수행한 후, 현재 표시되는 사용자 계정 (ID, Password 등) 입력 UI가 표시되어야 할 것 같습니다. 다른 분들의 생각은 어떠신지요?

**Comment by asdfljh** [comment]
저도 PGP인증 이후에 register information 입력부분이 나오는게 맞는 것 같습니다.

**Comment by jmpark81** [comment]
제가 그럼 이 부분을 제 local branch에서 하고 있어 볼게요.
오늘 얘기해보고 방향 잡으면 될 것 같네요.

**Comment by ggoboogy** [comment]
@asdfljh 네 맞습니다. 현재 그부분은 아직 구현전이고, 말씀하신것처럼 register를 선택했을때 PGP 인증이 먼저 이루어진 후 현재 구현된 화면으로 넘어가게끔 할 생각입니다.

**Comment by jmpark81** [comment]
@ggoboogy 제가 초안을 구현해볼게요. `auth`쪽 구현 검증을 위해서라도 클라이언트부터 인증 전과정을 구현해야할 것 같아요.

**Comment by jmpark81** [comment]
초안 구현이 완료되어 해당 이슈를 종료합니다.
