### ISSUE TITLE
[MySQL] PGP should be included in the database as a field.

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#3]
According to the document, one PGP can create various user accounts.
And, each PGP(not each account) will be get 1,000 won as an initial money.
Therefore, in order to avoid duplicated providing of money, DB(s) must contains a PGP field.
Or we may make an extra database in order to log each history about offering initial money, because a PGP should not get any more money even though he/she creates a new account after removing an existing one.

Thanks!

**Comment by ggoboogy** [comment]
Or we may make an extra database in order to log each history about offering initial money, because a PGP should not get any more money even though he/she creates a new account after removing an existing one.

**Comment by ian0371** [comment]
We are going to store PGP key in ascii text (just like the public keys uploaded in github).
