### ISSUE TITLE
Transfer message

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#30]
송금 시에 송금 메시지를 보낼 수 있는 UI가 필요합니다.
(이는 tran_table의 msg에 저장)

**Comment by ggoboogy** [comment]
I will fix it

**Comment by ggoboogy** [comment]
This issue is fixed.
See: [385d941](https://github.com/KAIST-IS521/TeamOne/commit/385d9414ea54f653c71665a98503cd595eb59577)
