### ISSUE TITLE
[DB bug] bankDB insert value 유효성 검사

### ISSUE THREAD

**Issue by asdfljh** [KAIST-IS521/TeamOne#36]
![image](https://cloud.githubusercontent.com/assets/26140051/26154535/d28210ae-3b4a-11e7-9dca-c8cab2bbf560.png)
https://github.com/KAIST-IS521/TeamOne/issues/12#issuecomment-302029710 에서 store_transaction을 UI를 통해서가 아니라 python3 interpreter에서 테스트해보다가 receiver에 계좌번호가 들어가는지 모르고, id를 실수로 입력했는데요. 위 그림과 같이 Warning만 발생하고 store가 되더라구요. DB를 확인해보니까, to_account에는 0이 저장되어있는데요. 문제는 mysql에서 invalid insert을 prevent 해줄거라 생각했는데, 잘 안된다는 점입니다.

@ian0371 @ggoboogy 
다른 일이 생겨서 그거 하고 있어서 찾아보진 못했습니다. 혹시 방법 아시거나 찾으시면 comment로 남겨주세요. (기존 이슈에 comment로 남길까했는데, 다른 함수도 테스트해봐야 할 듯 해서 새로 issue로 만들었습니다.)

**Comment by ian0371** [comment]
http://stackoverflow.com/questions/2262196/why-can-you-insert-characters-into-a-mysql-int-field
테이블 만들기 전에 SET sql_mode='STRICT_ALL_TABLES' 옵션을 줘야하나봅니다.

**Comment by ggoboogy** [comment]
계좌번호 대신 id 사용하여도 여전히 해당 이슈 유효한가요?

**Comment by ian0371** [comment]
general한 문제라 유효합니다.

**Comment by ian0371** [comment]
해당 문제는 MySQL 내부에서 string을 integer로 implicit casting을 하면서 발생하는 문제인데,
현재 지현씨가 말씀하신 대로 해당 함수에서는 더이상 문제가 되지 않는 부분입니다.
하지만 warning을 잡지 못하면 추후에 다른 곳에서도 문제가 발생할 수 있다고 판단하여 이슈를 열어두었으나, SET sql_mode='STRICT_ALL_TABLES'같은 옵션을 사용하여도 warning이 error로 바뀌지 않아 exception 처리하는 부분에 잡히지 않습니다.
이러한 부분을 해결하려면 MySQL의 implicit casting 기능을 끄는 방법이 필요한데, 이는 해결이 불가능해보입니다. @ggoboogy 님이 UI쪽에서 input 검증을 철저히 하는 수밖에 없을 것 같습니다.
