### ISSUE TITLE
[Auth][UI] Helper script for client

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#37]
별도의 클라이언트 프로그램은 아니지만  `netcat`을 통해 입력할 클라이언트의 응답값을 만들어줄 간단한 python script를 하나 만드는 것이 어떨까요? 
지금 초기 버전을 만들어 테스팅 중이에요.
사용 시나리오는 개인키가 import 되어 있다는 가정 하에 `passphrase`와 BASE64 encoding된 서버의 challenge를 argument로 python script에 전달하면 갖다붙일 수 있는 encoding된 응답값이 출력되는 것입니다.
팀원분들의 생각은 어떠세요?

**Comment by ian0371** [comment]
SLA에 포함시키면 되지 않을까요?

**Comment by jmpark81** [comment]
아~ 이런 기능들이 SLA인가 보네요.
이전에 설명해준 것을 생각해보니 SLA에 포함시켜도 될 것 같네요.

**Comment by jmpark81** [comment]
@ian0371  f378502 에 push 하였습니다.
간단한 python script와 사용법(`README.md`)을 push 하였습니다.
이에 본 이슈를 close 합니다.
