### ISSUE TITLE
[Auth][UI] Passing passphrase for server's private key

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#38]
서버용 개인키로 복호화를 하기 위해서는 passphrase를 알아야 합니다.
현재 `auth`는 하드 코딩 형태로 넣는 구조로 되어 있습니다.
이 경우, 저희 코드를 보면 서버용 개인키의 passphrase를 알 수 있어서 문제가 될 것 같습니다.
간단히 드는 생각으로는 서버의 `main.py`를 실행할 때 argument 형태로 넘겨주면 될 것 같은데, 
그럴 경우 저희 뱅킹 서버 취약점으로 인해 `shell`을 획득할 경우, 지난 activity 때의 공격 방식(`cat /proc/pid/cmdline`)을 통해 획득할 수 있을 것 같습니다.

좋은 방법 없을까요?

**Comment by ggoboogy** [comment]
쉘을 따게되면... 사실상 뭐든지 할수있기때문에 다른방법으로 한다고 해도 어떻게든 알아내게되지 않을까요....?ㅎ....

**Comment by jmpark81** [comment]
그럼 그냥 소스코드에 하드코딩하지 말고 argument 형태로 넘겨서 처리할까요?

**Comment by james010kim** [comment]
passphrase는 push할 때 지워주면 어떨까요?
flagupdate.py 에서도 서버 개인키로 복호화하여, passphrase는 일단 지워놨습니다.
[e9b3f2e](https://github.com/KAIST-IS521/TeamOne/commit/e9b3f2e980f47e985ef4634e4aad4d4fc04777c0)

**Comment by jmpark81** [comment]
@james010kim  이 코드를 pull하여 그대로 실행하는 것 아닌가요? 실행 전에 수정해서 passphrase를 하드코딩할 수 있나요? commandline으로 넘겨서 그 값을 내부에서 쓰면 될 것 같은데요.

**Comment by jmpark81** [comment]
command line argument를 통해 passphrase를 넘겨주도록 수정하였습니다. 1985538

**Comment by james010kim** [comment]
flagupdater 도 command line argument로 수정하여 issue를 close하겠습니다. https://github.com/KAIST-IS521/TeamOne/commit/0525b475132ce225746c2265fe58059f36e795a4
