### ISSUE TITLE
[Auth] install_gnupg.sh failed

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#4]
In my vagrant machine, `install_gnupg.sh` showed an error that said the lack of `setuptools`.
```
vagrant@deb32:~/TeamOne/auth/python-gnupg$ sudo make install
python setup.py install --record installed-files.txt
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    import setuptools
ImportError: No module named setuptools
Makefile:129: recipe for target 'install' failed
make: *** [install] Error 1
vagrant@deb32:~/TeamOne/auth/python-gnupg$ sudo apt-get install -y python-setuptools
```

I need to execute additional installation as follows:
```
> sudo apt-get install -y python-setuptools
```
Thus, `install_gnupg.sh` needs the revision to address this issue.
I will also check the countermeasure for this issue.

**Comment by james010kim** [comment]
Yes, setuptools needed. My vagrant already installed. We have to run under fresh vagrant. :)

**Comment by jmpark81** [comment]
It seems that `gnupg` is not installed for `python3`.
Any idea to install this module for `python3`.
Also, `python3-gnupg` is not compatible with this modified `gnupg`.

**Comment by jmpark81** [comment]
I solved above issue by `sudo pip3 install gnupg`.

**Comment by jmpark81** [comment]
bc9eeba 에서 `Makefile`로 대체 완료됨
