### ISSUE TITLE
[UI] show generated account number 

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#41]
should show generated account number in UI

**Comment by ggoboogy** [comment]
I think we don't need to show generated account number in UI, since we only use user id in every user menu. So I will close this issue.

**Comment by ian0371** [comment]
transaction history 보여줄 때 from과 to가 계좌번호로 출력되는데 자신의 계좌번호 몰라도 상관없을까요??

**Comment by ggoboogy** [comment]
@ian0371  from to 모두 id로 출력되게끔 UI 구현했어요 !

**Comment by ian0371** [comment]
@ggoboogy 아 그게 get_user_id함수인가요?
이렇게 하면 탈퇴한 유저의 ID는 가져오지 못합니다.
만약 withdraw_account_table에서 계좌로 ID를 가져오는 코드를 추가한다해도 탈퇴한 ID와 현재 ID가 같게 출력되는 문제가 있을 것 같습니다. 이를 간편하게 해결하려면 withdraw_account_table에서 가져온 경우 탈퇴한 ID라고 옆에 표시해주는 것도 좋을 것 같네요.

**Comment by ggoboogy** [comment]
아 그런문제가 있었네요 ㅠ 새로 이슈 다시 만들게요.
