### ISSUE TITLE
[UI] Paths to include the implemented modules

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#43]
개발한 python 모듈을 불러올 때 경로를 어떻게 지정할지 정해야할 것 같습니다.
저는 보통 최상위 폴더(`TeamOne`)에서 `python3 server/main.py`와 같은 형태로 실행을 합니다.
그러다 보니 `main.py`에서 사용하는 `utils` 경로가 맞지 않아서 오류를 발생시켰습니다.

향후 `README.md`를 작성할 때도 실행 방법을 명시해야할 것으로 보이니 기준을 정했으면 하는데 다른 팀원분들의 의견 부탁드립니다.

1. 실행 위치: 최상위 폴더인 `TeamOne`에서 실행하거나 `server` 폴더로 이동한 후 실행하거나 둘 중 하나를 정하면 어떨까 합니다.

2. 모듈 경로: 절대 경로(`/home/vagrant/TeamOne/`)로 하거나 실행 위치를 기준으로 상대 경로를 하거나 정해야할 것 같습니다.

**Comment by ggoboogy** [comment]
제가 main.py 에서 상대경로로 utils.py 임포트 한 부분이 에러가 발생했다는 말씀이신가요?

**Comment by ggoboogy** [comment]
추가적으로, 현재 auth.py 의 경우 절대경로로 구현하셨는데, 절대경로는 실행환경에 따라서 바뀌기 때문에 그전에 실행경로를 먼저 구하는 코드를 추가하거나 상대경로를 사용해야할것 같습니다.
이부분은 제가 일단 상대경로로 바꿔서 다시 커밋하겠습니다.

**Comment by jmpark81** [comment]
네, 그럼 상대 경로로 할 경우 'main.py'가 실행되는 위치를 fix하면 되겠네요.

**Comment by jmpark81** [comment]
@ggoboogy 현재 `main.py`가 `server` 폴더 내에서 실행되는 구조로 상대경로를 잡으신 것 같네요.
저도 우선 그게 맞춰서 수정하겠습니다.

**Comment by ggoboogy** [comment]
최종적으로 실행경로는 아마 최상위 디렉토리에서 파일하나를 만들어서 main을 호출하는 형식이 아닐까 싶습니다만..... 제가 파이썬으로 프로젝트 해본 경험이 없어서 이부분은 다른 팀원분들께서 의견을 주시면 감사하겠습니다.
@asdfljh  @ian0371 @james010kim

**Comment by ian0371** [comment]
글쎄요.. 저도 이런 건 안 해봐서.. 최상위폴더에 run.py 이런게 있어서 이것만 실행하면 편할 것 같네요.

**Comment by asdfljh** [comment]
저도 치현씨와 같은 의견입니다.

**Comment by ggoboogy** [comment]
Finished in [ecaf8dd](https://github.com/KAIST-IS521/TeamOne/commit/ecaf8ddd02a84e5fe350c95eb3b0e023fea066f0)
