### ISSUE TITLE
Atomicity of multiple queries

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#46]
store_transaction()같은 경우, 다음의 스텝으로 이루어져 있습니다.
1. 송신자의 balance update
2. 수신자의 balance update
3. transaction 기록
여기서 1번과 2번만 성공하고 3번이 실패할 경우 atomicity를 유지하도록 1, 2번까지 rollback을 시켜줘야 한다고 생각합니다. 현재는 이것이 고려가 안 된 상황입니다.

**Comment by ian0371** [comment]
@asdfljh #36 해결하면서 warning을 error로 바꾸고
http://stackoverflow.com/questions/9802102/python-mysql-when-to-explicitly-rollback-a-transaction
적용하면 될 것 같습니다.
이러면 autocommit=True를 빼고 모든 쿼리 보낸 뒤 commit() 하는게 좋아보이는데 어떻게 생각하세요?

**Comment by asdfljh** [comment]
넵. 좋은것 같습니다.

**Comment by ian0371** [comment]
@asdfljh 모든 쿼리 고쳐볼게요
