### ISSUE TITLE
[MySQL] is_valid_receiver 함수 관련 + 함수 추가

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#47]
1. 현재 UI에서 돈 이체시 valid 한 receiver 인지를 구현해주신 is_existing_id() 함수를 통해 확인하고 있습니다. 따라서 is_valid_receiver 함수를 다른곳에서 사용하고 있는게 아니라면, 없어도 무방할것 같습니다!

2. UI 쪽에서 get_account_num과 반대되는 get_user_id(account_num)라는 함수가 필요하게 되어 get_account_num 함수를 변형하여 추가하였습니다. see: [78f13cd](https://github.com/KAIST-IS521/TeamOne/commit/78f13cdd1add7091721e872dfa262f808bc6889e)

**Comment by ggoboogy** [comment]
@asdfljh  @ian0371  확인후 close 해주세욧

**Comment by ian0371** [comment]
is_valid_receiver()가 아무데서 안 쓰여서 488462a 에서 삭제했습니다.
