### ISSUE TITLE
[MySQL] store balance after transfer in tran_table

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#48]
I think balance after transfer should be stored in tran_table.
If you addressed this issue, plz leave a comment.

**Comment by asdfljh** [comment]
@ggoboogy 이 부분에서 from_account, to_account 두 계좌의 잔액이 필요하겠죠? 현재 함수 구현에서 from_balance, to_balance 두 개의 column을 추가로 입력받도록 수정하면 될까요? (balance를 가지고 와서 argument 처리는 UI에서)

1. db_schema 변경 필요.
2. store_transaction, get_all_transaction 변경 필요. - @ian0371

**Comment by ggoboogy** [comment]
네네 두 계좌의 잔액 칼럼 추가하셔서 하면 될거같고, 나머지는 UI에서 처리할게요.

**Comment by ian0371** [comment]
store_transaction fixed.
see: cf45565

**Comment by ggoboogy** [comment]
Good. Working well.
See: [5c2bf7c](https://github.com/KAIST-IS521/TeamOne/commit/5c2bf7c1e6af5b23d67fbc625deaeca754b89b55)
