### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#5]
We need to make DB schema using DDL.

**Comment by asdfljh** [comment]
DB schema prototype입니다.
Table 간 relationship을 어떻게 해줘야 할 지 모르겠어서 현재 diagram 상태를 올립니다.
![image](https://cloud.githubusercontent.com/assets/26140051/26037654/a7a70b6a-3932-11e7-9a5a-acb7cea0fa31.png)

**Comment by ggoboogy** [comment]
혹시 거래내역에 표시될 사용자이름(?)을 추가해야할까요?
거래내역 표시를 user_id로 하거나 아님 사용할 이름을 추가할 수 있을것 같은데, 어느쪽이 더 나을지 의견 부탁드립니다.

**Comment by asdfljh** [comment]
계좌번호와 github id가 좋지 않을까요?
일단은 github id로 해두고, 프로토타입 나오고 닉네임을 만들수 있게 추가 하면 좋을 것 같아요.

**Comment by asdfljh** [comment]
DB schema 1.0.1
foreign key 추가 버전 diagram입니다.
![image](https://cloud.githubusercontent.com/assets/26140051/26055849/a082b85e-39ad-11e7-9b88-65a28ca8d6be.png)

* Diagram 이미지 버전별로 업데이트하는 issue를 따로 만들까요? 의견주세요.

**Comment by ian0371** [comment]
issue말고 README나 다른 md문서에 넣어도 좋을듯해요

**Comment by jmpark81** [comment]
`auth_table`에서 pgp_key를 넣는 부분이 모호하다면 DB Schema에서는 제거해도될 것 같습니다.
`pubkeys` 폴더에서 `github_id`를 기준으로 `.pub` 파일을 읽어와서 활용하는 부분이 구현되어 있어서 파일로 읽어와도 무방할 것 같습니다.

**Comment by ian0371** [comment]
일단 pgp_key column이 있긴 한데, 이미 파일에서 읽는 방식으로 구현이 되었다면 필요없을 것 같은데 삭제하는게 좋을까요?

**Comment by jmpark81** [comment]
@ian0371 네, 삭제하셔도 될 것 같습니다.

**Comment by ian0371** [comment]
59d8656 에서 삭제되었습니다.
