### ISSUE TITLE
[UI][MySQL] Plz give me opinions about transfer history

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#51]
지금 현재 transfer history 조회 부분에서, 입출금 내역 sender 및 receiver 부분을 모두 user ID로 출력하고 있습니다. 그런데, 탈퇴한 회원인 경우를 고려하여 출력을 해야할 것같아 이부분에 대해 의견을 구하고자 합니다. 참고로 저는 이번 과제 UI 부분을 만들면서 실제 우리은행 뱅킹을 많이 참고했는데, 어떤 사람으로부터 돈을 이체받은 경우 sender의 계좌번호 같은 부분은 표시되어있지 않더라구요. 어쨌든! 아래에 예시를 몇개 적어둘테니 의견 부탁드릴게요. 추가적인 의견도 좋습니다.

1. user_id  : 탈퇴여부관계없이 user_id 만 출력
2. user_id (deleted account) : user_id + 탈퇴여부 출력
3. user_id (계좌번호)
4. 계좌번호만

**Comment by ggoboogy** [comment]
@asdfljh @ian0371 @james010kim @jmpark81

**Comment by ian0371** [comment]
3번 좋네요

**Comment by jmpark81** [comment]
1번이 1번인 이유가 있을 것 같은데, 전 구현이 편리한 쪽이 좋아 보입니다.
만약 그게 1번이라면 전 1번에 한 표 던집니다.

**Comment by asdfljh** [comment]
저는 ID중복 이슈 고려해서 3번이 좋을듯 합니다.

**Comment by james010kim** [comment]
가장 심플한 1번 또는 4번 추천입니다. ^^

**Comment by ggoboogy** [comment]
중복이슈 고려해서 전부 3번으로 대체하겠습니다.

**Comment by ggoboogy** [comment]
3번으로 전부 대체해서 구현 완료하였습니다.
See: [e76822e](https://github.com/KAIST-IS521/TeamOne/commit/e76822e74221a7c2531985e069aed7d9c2de2264)
