### ISSUE TITLE
[UI] Phone number

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#52]
등록과정 중에 폰번호를 입력하게 되어 있는데, 예제로 `(ex. 01x-xxxx-xxxx)`라고 되어 있습니다.
실제로 `01x-xxxx-xxxx`라고 입력하면 정상적으로 처리되지 않고 `01xxxxxxxxx`처럼 `-`를 빼야지만 정상적으로 입력됩니다. 
수정이 필요해보입니다.

**Comment by ggoboogy** [comment]
핸드폰번호 입력 관련 regular expression 및 guide 모두 digit only로 수정하였습니다.
see : [4f5f878](https://github.com/KAIST-IS521/TeamOne/commit/4f5f8780c9c953ad9a495fe145f6d214ad30086f)

**Comment by jmpark81** [comment]
네, 그럼 이슈 Close 하겠습니다. 고생 많아요~^^
