### ISSUE TITLE
[Auth][DB] Admin account and flag updater

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#57]
`engineering.tex`에 의하면 flag updater는 다음과 같이 동작해야 합니다.

> Finally, you need to implement a flag updater (see §1.6). 
> Your flag updater gets a JSON message, verifies the signature of the message, and updates the email address field of “admin” with the given flag string.

__the email address field of “admin”__ 이기에 `db`의 사용자 필드 중 email이 있어야 하는 것으로 보입니다.
(그래서 현재 저희 팀의 `db`에는 email 필드가 있는 것으로 보입니다. 맞죠?)
그렇다 하면, `Makefile` 등을 통해 default 계정으로 `admin`이 포함되어야 함을 의미합니다.
이에 따라 `flag updater`는 전달 받은 `flag`를 `db`에다가 갱신해야 하는 것으로 보입니다.

이 해석이 맞다면 최초 `db` 셋팅 (`Makefile`을 통해 또는 다른 방법을 통해 `admin` 계정 생성)이 필요하며,
`flag updater`는 이에 맞춰 동작해야할 것 같습니다.

다른 분들 이견 있으신가요?

**Comment by james010kim** [comment]
그렇네요. flag를 db에 보관해야 하네요. (지금은 파일로 저장)
flag updater에서 사용할 수 있는 함수가 있으면 좋겠습니다. ^^
대략 이런 모양으로요.

```
bank = utils.bankDB()
bank.setflag(newflag)

```

**Comment by jmpark81** [comment]
`flag updater`를 `sudo`로 실행해야할 특별한 이유가 있나요?
궁금해서 여쭤봅니다~^^

**Comment by james010kim** [comment]
바인딩할 포트가 42번인데 1024번 이하는 privileged port라서 root 권한이 필요했습니다. :)

**Comment by asdfljh** [comment]
현재 user_table에 admin 계정을 추가하기 위해서는 admin 계정에 맞는 github_id가 auth_table에 존재해야 합니다. TA's id가 github_id.list에 다 있나요?

**Comment by james010kim** [comment]
네. 3명으로 알고 있어요. 모두 다 github_id.list에 있습니다. auth/tapubkey/*.pub 에 3명의 키가 있어요.

**Comment by asdfljh** [comment]
기존의 user_table에 넣는다면 admin에서 주어지지 않는 나머지 컬럼은 임의값으로 그냥 insert할까요?

**Comment by james010kim** [comment]
네. 그 방법도 괜찮을 것 같습니다. 
한가지 user_pw는 추측하기 어렵게 만들면 좋을 것 같습니다.

**Comment by jmpark81** [comment]
admin 계정은 쓸 일이 없는 계정이지 않을까요?
github_id나 user_pw 등 모두 임의로 어렵게 만들어도 될 것 같아요.

**Comment by ian0371** [comment]
f2880ea 에 set_flag()함수 추가했습니다.

**Comment by james010kim** [comment]
flag update message 전송 테스트 결과, 문제없음을 확인하여, close하겠습니다.
테스트용 flag new update 메시지(james010kim:thisisnewflag)를 참고로 첨부합니다.
```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA58aVaCe/dr4AQf9F/lahCfO1CkGL96CHDvcF7QBAYp485aFERNrq+lgKzIn
dClWzmhVmSJOmiNSmxYpZkN6OEUCCJh1d/AUKBuEr/B18G1/8sLQyzeDRXL5UGs0
vLQiJGx3nWTI2C9MP7HtQ4pYU0fVjiFvvmFOejXFhha2/uRWy7NOVOoEvuYZOtnN
AHDfY6VW/KJHEVDfMvqGv2K7rzz8jP5gvvgN65/v+GeCqoKT9oK8l9uvJVaWhjoq
f/jbKvmWj7p6sLxv5MrPuQuG6pTuffqjNJcv7K77Ve+v++P6NYdEa3RfUOZdUI6y
h1MX3wUWIb6nD3bo/hVXJitIvZqZGBgNkV2aWgLb9tLBCgFflgmfQebxtyUSQ96G
+H2PDa8buaz5kWLD8m14/1Cuh9nWcG9CpjW9lKKSLMaK415S1KuT/Z35w715CbXw
t6yyoG+ZhTj3ikwr8/rz7sYyZTtQowG1cRD5vNKnhDtkwfAeRLByZgBVzrnYeXbi
gkllSUJ7uegoS5Qf80H61kdYjccRYHepoKyNbzj8Ie4ItX7ZuJ33CiWBBcwI+FPe
SgosH/zTVMd7pdyxB/5zFvo6dMO2uYxuX7P5P0QFz14vz9FThKkT2nl0pddMZ26V
e7qn9ey+dXyn8ToWuR3m3l5FQXnDdVZEg0KgAySuie2GUOOZ/T2dakDHHHFqJ1mC
opk0t30oHUXtwrQ/F3Eib0WEfiZd7olT2/NdCCSBTD47KGPecEorz+MkaCpv05jO
wjp21BTV0uBvc+tkm5fE8mo67IIaT7RtQWnx1mXe4TSK3cqmjlx4eVqJvViMHpnI
amOW+xlTd/q0oF+8RJUxQhnIIol93wyDLvin1lCRnBqqrgO9zGEhB/9Ews1wsR7T
8//5KE6vkAcMjXLNT9jnGCa6hWcbeJGdcuxmdhKfH72W/vRiEbhoumeAO5Tpz34T
UEFLSf1U1XCDkozo
=ZmYa
-----END PGP MESSAGE-----
```
