### ISSUE TITLE
Give new user 1000won

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#59]
처음 가입한 사람(github_id)에게 1000원 주는 기능이 필요합니다.
다음과 같은 코드 추가하면 될 것 같습니다.
```python
if obj.get_reg_flag(github_id) == 0:
    balance = 1000
else:
    balance = 0
```
get_reg_flag(): d0297dd

참고로  f2880ea 이후에서 store_user() 함수는 해당 github_id의 reg_flag를 1로 세팅합니다.
따라서 등록하는 사용자에 대하여 reg_flag를 1로 세팅하는 작업이 UI쪽에서 필요 없습니다.

**Comment by ggoboogy** [comment]
I will fix it by tomorrow.

**Comment by ggoboogy** [comment]
Fixed in [988e80c](https://github.com/KAIST-IS521/TeamOne/commit/988e80cb2e24fd7bd1e98d82f710d644ff8f2e73)
