### ISSUE TITLE
Server need to be threaded

### ISSUE THREAD

**Issue by ian0371** [KAIST-IS521/TeamOne#6]
Now the server is implemented in naive listen/accept, with which two or more users cannot be connected simultaneously.
It has to be implemented using multithread.

**Comment by ggoboogy** [comment]
I'm aware of it and It will be fixed in today.
Thanks to remind me!

**Comment by ggoboogy** [comment]
Fixed in [2478395](https://github.com/KAIST-IS521/TeamOne/commit/247839516698196db6c1d6d650b108adc95197d0).

**Comment by ian0371** [comment]
Auth team also need to fix this.

**Comment by ian0371** [comment]
Misunderstood. No more issue.
