### ISSUE TITLE
Things to do before deadline

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#60]
이제 제출이 얼마 안남았기 때문에 남은 작업들과 제출 전까지 확인해야할 작업들 리스트업 하면 좋을거같아요.
제가 확인했을때는,

1. server 폴더 내에 README.md 파일 (-> assign @ggoboogy)
2. auth 폴더 내에 README.md 파일
3. 모든 코드 라인당 80글자 넘지 않는지 확인
4. 모든 코드 TAB 있으면 제거
5. 모든 코드 코멘트 잘 달았는지 확인
6. 최종 실행경로 세팅 (issue #43)

정도 인것 같은데..... 혹시 더 있나요...? 코멘트 부탁드려욧..!

**Comment by ggoboogy** [comment]
@ian0371 @asdfljh @james010kim @jmpark81

**Comment by ian0371** [comment]
make 테스트할 때 교수님이 주신 초기 상태의 VM에서 잘 돌아가는지 확인해야 할 것 같아요.

**Comment by jmpark81** [comment]
1) `SLA`를 구현할 부분이 있으면 구현하는 것이 어떨까요?

2) 최상위 `README.md` 부분에는 각 메뉴별 실행 예시를 작성하는 것도 좋을 것 같습니다.  (-> assign @jmpark81)

3) PGP 인증 변경에 따른 `auth.py`와 `gen_response.py`의 수정이 필요하며 이 부분은 내일 수업 전까지 정리할 생각입니다. (-> assign @jmpark81)
