### ISSUE TITLE
Check every code according to the guideline

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#66]
db 및 auth 대표 한분이 아래 사항에 대해 모두 확인해주시고 코멘트 달아주세요.
(auth 및 db **폴더 내에있는 모든 코드** 확인해주세요)

1. 모든 코드 라인당 80글자 넘지 않는지 확인
2. 모든 코드 TAB 있으면 제거
3. 모든 코드 코멘트 잘 달았는지 확인

server폴더 안에 있는 모든 코드에 대해서는 제가 확인하고 코멘트 달도록 하겠습니다.

**Comment by ggoboogy** [comment]
Server is done.
See : [a2e0cb2](https://github.com/KAIST-IS521/TeamOne/commit/a2e0cb24bbcac8d4f3a50fcdbaac8eda8932cc8f)

**Comment by ian0371** [comment]
838787f 기준입니다.
1. grep -n '^.\{80\}' * -r
create_bankdb.sql와 get_pubkey.sh가 걸립니다. 하지만 고쳐야될지 모르겠네요.
2. grep -P "\t" * -r
Makefile 외 해당 없습니다.
3. utils.py에 코멘트가 별로 없습니다..

**Comment by jmpark81** [comment]
838787f 기준으로 auth도 문제 없어 보입니다.

**Comment by ggoboogy** [comment]
@asdfljh @ian0371
utils.py에 코멘트가 가뭄이군요....ㅋㅋ
이부분만 해결되면 이슈 클로즈 해도 될거같아요..ㅠㅠ

**Comment by ggoboogy** [comment]
모든 부분 확인되어 이슈 클로즈 합니다.
comments in utils.py see : [581c4eb](https://github.com/KAIST-IS521/TeamOne/commit/581c4eb20334caac088ad1d8d5cf1fd555abd23d)
