### ISSUE TITLE
Remove SQL root password

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#72]
현재 코드상에서 모든 루트패스워드 삭제하고, 파일에서 패스워드 읽어오는 형식으로 변경해야할것 같습니다. 
당연히 패스워드 파일 또한 깃에 올리면 안되고, 지금 현재 패스워드가 이미 깃에 로깅된 상태라 패스워드 변경도 해야할것 같습니다.

1. 모든 코드에서 루트패스워드 삭제
2. 루트패스워드 필요한부분 파일에서 읽어오게끔 수정

**Comment by ggoboogy** [comment]
@asdfljh @ian0371

**Comment by ian0371** [comment]
1551de6 체크 후 merge해주세요.
