### ISSUE TITLE
Error in build script

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/TeamOne#75]
Hi, this is TA examining your team project. Please solve the following issue.

`db/Makefile` trieggers `setup_mysql.sh` first, and then executes `sudo pip3 install PyMySQL`. However, `setup_mysql.sh` internally runs `python3 reg_*.py` scripts, which depends on PyMYSQL library. This raises error when building your project in pure docker image.

Thank you.

**Comment by ian0371** [comment]
Fixed in 71212dc.
Please check if the same problem occurs in the branch.
I confirmed that it works in docker image zcalusic/debian-jessie-i386.

**Comment by jchoi2022** [comment]
The script now works fine in my docker image, too. Please merge the branch to master branch. Thanks for the fix!
