### ISSUE TITLE
Logic error in recv_encrypted()

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/TeamOne#76]
Hi, this is TA examining your team project. Please solve the following issue.

Current `recv_encrypted()` calls `conn.recv(1024)` iteratively, and terminates when the received data is equal to '-----END PGP MESSAGE-----\n'. Thus, client has to send the last line of the encrypted response with a separate send() call. Please fix the logic to allow a client to send the whole encrypted response at once.

Thank you.

**Comment by jmpark81** [comment]
I used `nc` for the client, and I don't have to invoke an additional `send()` call in this environment.
The client only needs to copy and paste his/her encrypted response, that is generated by `gpg` command line, in the terminal. 
Can I ask you about your experiment environment?

**Comment by jmpark81** [comment]
Hi, I could catch your point while implementing the SLA checker.
Yes, you're right. The SLA checker should call an additional call of `send()` for the current implementation.
I fixed this issue in 9cf9dce.

**Comment by jchoi2022** [comment]
I confirmed the issue is correctly fixed, too. Thanks for the fix!
