### ISSUE TITLE
Incomplete SLA checker

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/TeamOne#77]
Hi, this is TA examining your team project. 

Since other teams need your SLA checker to test whether they successfully deployed your code, please complete the SLA checker as soon as possible. Both `sla_login.c` and `sla_auth.c` need a lot of improvement.

Thank you.

**Comment by jmpark81** [comment]
`sla_auth.c`, which conducts the PGP-authentication with the `bank` server, is completed in 52eb3fd.

**Comment by ian0371** [comment]
@jmpark81 @james010kim main 인자의 ip, port 제외한 나머지 인자(private key나 passphrase 파일 경로) 하드코딩해서 박아주세요.

**Comment by jmpark81** [comment]
Fixed in e053ecf.
The command line arguments are reduced to `ip`, `port`, and `github_id`.

**Comment by jchoi2022** [comment]
Still, the code that checks features like withdraw or transfer does not carefully examine the data returned from the server. It concludes everything is fine if the received data does not contain "** Login fail **" string, which can be very misleading. In an extreme case, even if the router blocks all the outgoing data except for the ">", current SLA checker will still be passed.  We rather expected the SLA checker to thoroughly test whether  whether correct amount of money are updated, whether the relevant information are correctly recorded in transaction history, and so on.

Anyway, still thanks for your efforts to fix the issue. From now on TA team will handle the issue to implement SLA checker.

**Comment by ggoboogy** [comment]
Thank you for your specific comments about it... cheer up.. be happy...
