### ISSUE TITLE
Initial design of PGP-based authentication

### ISSUE THREAD

**Issue by jmpark81** [KAIST-IS521/TeamOne#8]
According to the `engineering.tex`, I designed a simple PGP-based authentication.
Actually, the authentication scheme was already defined sufficiently in the `engineering.tex` file.

```
1) User --- (Attempt the registration via UI) --> Server (`UI`)
2) User <-- (Request a github ID) --- Server (`UI`)
3) User --- (Response with his/her github ID) --> Server (`UI`---(github ID)-->`Auth`)
4) User <-- ({N}pk_user || Cert_server) --- Server (`UI` <--`Auth`)
5) User --- ({N}pk_server) --> Server (`UI` --> `Auth`)
6) User <-- (Result) --- Server (`UI` <-- `Auth`)
```

In step 5, the server can check if the user decrypts the original random number (`N`) successfully.
If `N` is not matched with the one generated for this user, this authentication should be failed.

To process the multiple authentication requests, the authentication module seems to consider the session management.
Or the module needs to interwork with the database to manage (`insert` and `get`) the random number (`N`) for each authentication attempt. 

We need to think about pros. and cons. on this issue.
Is there any good idea?

**Comment by ian0371** [comment]
UI쪽에서 random N을 가지고있고, encrypt(N, github_id)로 auth에 넘기면 encrypt된 숫자를 반환하고 5에서 보낸걸 UI에서 if N == decrypt(received_message)로 체크하면 어떨까요?

**Comment by jmpark81** [comment]
@ian0371 네, 의견주신 것처럼 구현해서 605f787 에 push했습니다.
위의 설계안대로 구현이 완료되어 본 이슈는 close 하겠습니다.
