### ISSUE TITLE
[UI][MySQL] UI for login

### ISSUE THREAD

**Issue by ggoboogy** [KAIST-IS521/TeamOne#9]
[Login]
1. get username
2. get password
3. request DB for authentication

**[MySQL]**
**1. boolean = match_id_pw(id, pw)**

**Comment by ggoboogy** [comment]
1 & 2 is finished
see: [1e6ff48](https://github.com/KAIST-IS521/TeamOne/commit/1e6ff48eca1482534342823de19215a54a2ddeae)

**Comment by ian0371** [comment]
3 done.
see: f817719

**Comment by ggoboogy** [comment]
Good. working well
See: [a88f980](https://github.com/KAIST-IS521/TeamOne/commit/a88f9804bb244e1a596310a7cf42045bc3b038b0)
